### ISSUE TITLE
Error: Message 'isSymbol' not understood.

### ISSUE THREAD

**Issue by pspbar** [madskjeldgaard/HarmonicToolkitSC#2]
Totally new user of SC, after install the quark, boot the server and evaluate this line:

`var h = Harmony.new(\major);`

I get this error

`
        Harmony:init
                arg this = <instance of Harmony>
                arg intervals = 'major'
        < closed FunctionDef >
                var h = nil
        Interpreter:interpretPrintCmdLine
                arg this = <instance of Interpreter>
                var res = nil
                var func = <instance of Function>
                var code = "var h = Harmony.new(\major);
"
                var doc = nil
                var ideClass = nil
        Process:interpretPrintCmdLine
                arg this = <instance of Main>
^^ ERROR: Message 'isSymbol' not understood.
Perhaps you misspelled 'asSymbol', or meant to call 'isSymbol' on another receiver?
RECEIVER: major

`
`

**Comment by madskjeldgaard** [comment]
Hi. Thanks for the report. I just pushed a change that should fix it. Try installing it again :)

**Comment by pspbar** [comment]
Tried it, Quark: HarmonicToolkitSC[4c1cb53c338668221388ae6d0947c327cfc7f452]

But still getting the same error.

**Comment by madskjeldgaard** [comment]
> Tried it, Quark: HarmonicToolkitSC[4c1cb53c338668221388ae6d0947c327cfc7f452]
> 
> But still getting the same error. 

Did you recompile after reinstalling ? The problem is ddwCommon as missing dependency

**Comment by igormpc** [comment]
installed here, installed ddwCommon, recompiled, another error:

```
ERROR: Message 'removeDuplicates' not understood.
RECEIVER:
Instance of Array {    (0x5f88e4bb51b8, gc=F0, fmt=01, flg=00, set=02)
  indexed slots [4]
      0 : Integer 0
      1 : Integer 4
      2 : Integer 7
      3 : Integer 11
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = [*4]
		arg selector = 'removeDuplicates'
		arg args = [*0]
	< closed FunctionDef >
		var h = <instance of Harmony>
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
// Can be initialized with..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'removeDuplicates' not understood.
RECEIVER: [ 0, 4, 7, 11 ]
```

**Comment by madskjeldgaard** [comment]
> installed here, installed ddwCommon, recompiled, another error:
> 
> ```
> ERROR: Message 'removeDuplicates' not understood.
> RECEIVER:
> Instance of Array {    (0x5f88e4bb51b8, gc=F0, fmt=01, flg=00, set=02)
>   indexed slots [4]
>       0 : Integer 0
>       1 : Integer 4
>       2 : Integer 7
>       3 : Integer 11
> }
> ARGS:
> CALL STACK:
> 	DoesNotUnderstandError:reportError
> 		arg this = <instance of DoesNotUnderstandError>
> 	Nil:handleError
> 		arg this = nil
> 		arg error = <instance of DoesNotUnderstandError>
> 	Thread:handleError
> 		arg this = <instance of Thread>
> 		arg error = <instance of DoesNotUnderstandError>
> 	Object:throw
> 		arg this = <instance of DoesNotUnderstandError>
> 	Object:doesNotUnderstand
> 		arg this = [*4]
> 		arg selector = 'removeDuplicates'
> 		arg args = [*0]
> 	< closed FunctionDef >
> 		var h = <instance of Harmony>
> 	Interpreter:interpretPrintCmdLine
> 		arg this = <instance of Interpreter>
> 		var res = nil
> 		var func = <instance of Function>
> 		var code = "(
> // Can be initialized with..."
> 		var doc = nil
> 		var ideClass = <instance of Meta_ScIDE>
> 	Process:interpretPrintCmdLine
> 		arg this = <instance of Main>
> ^^ ERROR: Message 'removeDuplicates' not understood.
> RECEIVER: [ 0, 4, 7, 11 ]
> ```

Please try again now. Just pushed some more missing dependencies. Please reinstall it and recompile and see if it errors again :)

**Comment by igormpc** [comment]
fosc & JoshMisc deps didnt install. same errors. [i think i had wslib before, dont remember]

**Comment by madskjeldgaard** [comment]
> fosc & JoshMisc deps didnt install. same errors. [i think i had wslib before, dont remember]

Try running 

```
Quarks.uninstall("harmonics");
Quarks.uninstall("HarmonicToolkitSC");
```
Then recompile and run 
```
Quarks.install("https://github.com/madskjeldgaard/HarmonicToolkitSC")
```

**Comment by pspbar** [comment]
Stll no luck, recompiled, same error, uninstalled and installed again, then recompiled, same error.

**Comment by madskjeldgaard** [comment]
> Stll no luck, recompiled, same error, uninstalled and installed again, then recompiled, same error.

Could you please try once more ? I just pushed another change. It seems ddwCommon wasn't installed. 

Then after reinstalling and recompileing, run ```Quarks.gui``` and see if ddwCommon is listed as installed.

**Comment by pspbar** [comment]
Tried again, the same, ddwCommon is not installed.

**Comment by igormpc** [comment]
i installed manually JoshMisc and fosc before reinstalled. works ok now! :)

**Comment by pspbar** [comment]
Installing manually JoshMisc and fosc did the trick, no need to reinstall HarmonicToolkitSC. 
Now to make some noises. :)
I don't know if I should close the issue, because at the moment, it needs previous steps before installation to work.

Also, I've got an spare machine with a blank SC that can be used to test the Quark installer.

**Comment by madskjeldgaard** [comment]
I still don't understand why the dependencies do not install automatically but please try again now. I have now completely removed the .isSymbol call.

**Comment by k3vinpark** [comment]
I had manually installed the dependencies so it's all working for me now before your latest update. If you can give me some guidance into what and how I should remove any of these dependencies to test your latest update, I'd be happy to do so!

**Comment by kamidev** [comment]
Manually installing fosc and JoshMisc works for me too. And I agree with other users, the ambient example is nice!

But I just tried removing those dependencies, recompiling and reinstalling your latest fix: HarmonicToolkitSC https://github.com/madskjeldgaard/HarmonicToolkitSC/commit/f40504c33f0727309ac7cc451e513e7650018d51. But for me, that doesn't pull in those dependencies. I still have to install them automatically. 

I am on a Mac, if that makes any difference.

**Comment by madskjeldgaard** [comment]
I have tried fixing it again now. If anyone wants to test and let me know if works, that'd be greaet

**Comment by madskjeldgaard** [comment]
This was caused by this bug in SC 

https://github.com/supercollider/supercollider/issues/5345
